"""Small dependency-free dashboard page served directly by FastAPI."""

from __future__ import annotations

DASHBOARD_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PETLIBRO Local Relay</title><style>
:root{color-scheme:dark;--bg:#101419;--panel:#18212b;--muted:#99a9b8;--ok:#26b477;--warn:#e8a23d;--bad:#df5959;--line:#2a3948}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#edf3f8;font:14px system-ui,sans-serif}header{padding:18px 24px;border-bottom:1px solid var(--line);position:sticky;top:0;background:#101419;z-index:2}h1{margin:0 0 10px;font-size:21px}.status{display:flex;gap:14px;flex-wrap:wrap}.badge{padding:4px 9px;border-radius:14px;background:#25313d}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}nav{display:flex;overflow:auto;gap:4px;padding:12px 20px;border-bottom:1px solid var(--line)}button{background:#243240;color:#eaf2f8;border:0;border-radius:5px;padding:8px 12px;cursor:pointer}button.active{background:#3978a8}main{padding:20px;max-width:1400px;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.card{background:var(--panel);padding:14px;border-radius:7px;border:1px solid var(--line)}h2{font-size:16px;margin:0 0 10px}pre{white-space:pre-wrap;word-break:break-word;margin:0;color:#c8d8e7}table{border-collapse:collapse;width:100%}td,th{padding:8px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.muted{color:var(--muted)}.hidden{display:none}#logs{height:60vh;overflow:auto;font:12px ui-monospace,monospace;background:#090c10;padding:10px}.line{padding:2px 0}.ERROR,.CRITICAL{color:#ff8585}.WARNING{color:#ffcf72}@media(max-width:600px){main{padding:12px}header{padding:14px}}
</style></head><body><header><h1>PETLIBRO Local Relay</h1><div class="status" id="header">Loading…</div></header>
<nav id="tabs"></nav><main><section id="Overview"></section><section id="Cloud" class="hidden"></section><section id="Devices" class="hidden"></section><section id="Queues" class="hidden"></section><section id="State" class="hidden"></section><section id="NTP" class="hidden"></section><section id="Logs" class="hidden"><div class="card"><h2>Live logs</h2><div id="logs"></div></div></section><section id="System" class="hidden"></section></main>
<script>
const tabs=['Overview','Cloud','Devices','Queues','State','NTP','Logs','System'];let active='Overview';const get=async p=>(await fetch(p)).json();const esc=v=>String(v??'—').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const json=v=>esc(JSON.stringify(v,null,2));
function badge(label,value,ok){return `<span class="badge ${ok?'ok':value==='DISABLED'?'muted':'bad'}">${esc(label)}: ${esc(value)}</span>`}function card(title,body){return `<div class="card"><h2>${title}</h2>${body}</div>`}
function tabSetup(){document.querySelector('#tabs').innerHTML=tabs.map(t=>`<button class="${t===active?'active':''}" onclick="show('${t}')">${t}</button>`).join('')}function show(tab){active=tab;tabs.forEach(t=>document.getElementById(t).classList.toggle('hidden',t!==tab));tabSetup();refresh()}
async function refresh(){const status=await get('/api/status');const up=status.upstream;document.querySelector('#header').innerHTML=[badge('Relay','RUNNING',true),badge('Local MQTT',status.local_mqtt.connected?'ONLINE':'OFFLINE',status.local_mqtt.connected),badge('PETLIBRO MQTT',up.state,up.state==='ONLINE'),badge('Device',status.device?'KNOWN':'WAITING',!!status.device)].join('');if(active==='Overview')overview(status);if(active==='Cloud')cloud(await get('/api/cloud'));if(active==='Devices')devices(await get('/api/devices'));if(active==='Queues')queues(await get('/api/queues?limit=50'));if(active==='State')state(await get('/api/state'));if(active==='NTP')ntp(await get('/api/ntp'));if(active==='System')system(await get('/api/system'));}
function overview(s){document.querySelector('#Overview').innerHTML=`<div class="grid">${card('Relay',`<pre>${json(s.relay)}</pre>`)}${card('Upstream',`<pre>${json(s.upstream)}</pre>`)}${card('Queues',`<pre>${json(s.queues)}</pre>`)}${card('State shadow',`<pre>${json(s.state_shadow)}</pre>`)}${card('Local responder',`<pre>${json(s.local_responder)}</pre>`)}</div>`}
function cloud(c){document.querySelector('#Cloud').innerHTML=`${card('PETLIBRO MQTT',`<pre>${json(c.upstream)}</pre>`)}${card('Timeline',`<pre>${json(c.events)}</pre>`)}`}
function devices(d){document.querySelector('#Devices').innerHTML=`${card('Active device',`<pre>${json(d.active)}</pre>`)}${card('Candidates',`<pre>${json(d.candidates)}</pre>`)}`}
function queues(q){document.querySelector('#Queues').innerHTML=`${card('Device → Cloud',`<pre>${json(q.device_to_cloud)}</pre>`)}${card('Cloud → Device',`<pre>${json(q.cloud_to_device)}</pre>`)}`}
function state(s){document.querySelector('#State').innerHTML=`${card('Reported',`<pre>${json(s.reported)}</pre>`)}${card('Cloud desired',`<pre>${json(s.desired)}</pre>`)}${card('Feeding plans',`<pre>${json(s.feeding_plans)}</pre>`)}${card('Raw messages',`<pre>${json(s.raw_messages)}</pre>`)}`}
function ntp(n){document.querySelector('#NTP').innerHTML=`${card('NTP watcher',`<pre>${json(n)}</pre>`)}`}
function system(s){document.querySelector('#System').innerHTML=card('System',`<pre>${json(s)}</pre>`)}
function logs(){const box=document.querySelector('#logs');new EventSource('/api/logs/stream').addEventListener('log',event=>{const item=JSON.parse(event.data);const row=document.createElement('div');row.className='line '+item.level;row.textContent=`${new Date(item.timestamp*1000).toLocaleTimeString()} ${item.level} ${item.component}: ${item.message}`;box.append(row);if(box.children.length>5000)box.firstChild.remove();box.scrollTop=box.scrollHeight})}
tabSetup();refresh();setInterval(refresh,3000);logs();
</script></body></html>"""
